// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: rpc/http.proto

package hmacauthz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespCommon *HttpResponseCommon `protobuf:"bytes,1,opt,name=resp_common,json=respCommon,proto3" json:"resp_common,omitempty"`
	RespData   *anypb.Any          `protobuf:"bytes,2,opt,name=resp_data,json=respData,proto3" json:"resp_data,omitempty"`
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_rpc_http_proto_rawDescGZIP(), []int{0}
}

func (x *HttpResponse) GetRespCommon() *HttpResponseCommon {
	if x != nil {
		return x.RespCommon
	}
	return nil
}

func (x *HttpResponse) GetRespData() *anypb.Any {
	if x != nil {
		return x.RespData
	}
	return nil
}

type HttpResponseCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 状态码，0表示正常
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 信息提示，成功时为“OK”
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求id
	RetryMs   int32  `protobuf:"varint,4,opt,name=retry_ms,json=retryMs,proto3" json:"retry_ms,omitempty"`      // 失败时重试延迟，单位毫秒
}

func (x *HttpResponseCommon) Reset() {
	*x = HttpResponseCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpResponseCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseCommon) ProtoMessage() {}

func (x *HttpResponseCommon) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseCommon.ProtoReflect.Descriptor instead.
func (*HttpResponseCommon) Descriptor() ([]byte, []int) {
	return file_rpc_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpResponseCommon) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HttpResponseCommon) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HttpResponseCommon) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponseCommon) GetRetryMs() int32 {
	if x != nil {
		return x.RetryMs
	}
	return 0
}

var File_rpc_http_proto protoreflect.FileDescriptor

var file_rpc_http_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x28, 0x67, 0x6f, 0x70, 0x6b, 0x67, 0x2e, 0x6d, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x63, 0x6e, 0x2e, 0x6d, 0x74, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x70, 0x63, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x67, 0x6f,
	0x70, 0x6b, 0x67, 0x2e, 0x6d, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6e, 0x2e,
	0x6d, 0x74, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7c, 0x0a, 0x12, 0x48, 0x74, 0x74, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x4d, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x6f, 0x70, 0x6b, 0x67, 0x2e,
	0x6d, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6e, 0x2f, 0x6d, 0x74, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x3b,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_http_proto_rawDescOnce sync.Once
	file_rpc_http_proto_rawDescData = file_rpc_http_proto_rawDesc
)

func file_rpc_http_proto_rawDescGZIP() []byte {
	file_rpc_http_proto_rawDescOnce.Do(func() {
		file_rpc_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_http_proto_rawDescData)
	})
	return file_rpc_http_proto_rawDescData
}

var file_rpc_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_http_proto_goTypes = []interface{}{
	(*HttpResponse)(nil),       // 0: gopkg.mingting.cn.mtapis.v2.genproto.rpc.HttpResponse
	(*HttpResponseCommon)(nil), // 1: gopkg.mingting.cn.mtapis.v2.genproto.rpc.HttpResponseCommon
	(*anypb.Any)(nil),          // 2: google.protobuf.Any
}
var file_rpc_http_proto_depIdxs = []int32{
	1, // 0: gopkg.mingting.cn.mtapis.v2.genproto.rpc.HttpResponse.resp_common:type_name -> gopkg.mingting.cn.mtapis.v2.genproto.rpc.HttpResponseCommon
	2, // 1: gopkg.mingting.cn.mtapis.v2.genproto.rpc.HttpResponse.resp_data:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_http_proto_init() }
func file_rpc_http_proto_init() {
	if File_rpc_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpResponseCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_http_proto_goTypes,
		DependencyIndexes: file_rpc_http_proto_depIdxs,
		MessageInfos:      file_rpc_http_proto_msgTypes,
	}.Build()
	File_rpc_http_proto = out.File
	file_rpc_http_proto_rawDesc = nil
	file_rpc_http_proto_goTypes = nil
	file_rpc_http_proto_depIdxs = nil
}
