// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: api/service/queryservice.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询最近版本请求体.
type GetVersionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // 接收人
}

func (x *GetVersionsRequest) Reset() {
	*x = GetVersionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_queryservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionsRequest) ProtoMessage() {}

func (x *GetVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_queryservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_service_queryservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetVersionsRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

// 查询最近版本响应体.
type GetVersionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatestVersions []string `protobuf:"bytes,1,rep,name=LatestVersions,proto3" json:"LatestVersions,omitempty"` // 最新的版本号，最多5个
}

func (x *GetVersionsResponse) Reset() {
	*x = GetVersionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_queryservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionsResponse) ProtoMessage() {}

func (x *GetVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_queryservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionsResponse.ProtoReflect.Descriptor instead.
func (*GetVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_service_queryservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionsResponse) GetLatestVersions() []string {
	if x != nil {
		return x.LatestVersions
	}
	return nil
}

// 获取版本文件信息请求体.
type GetVersionFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // 接收人
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`     // 版本号
}

func (x *GetVersionFilesRequest) Reset() {
	*x = GetVersionFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_queryservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionFilesRequest) ProtoMessage() {}

func (x *GetVersionFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_queryservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionFilesRequest.ProtoReflect.Descriptor instead.
func (*GetVersionFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_service_queryservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetVersionFilesRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *GetVersionFilesRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 获取版本文件信息响应体.
type GetVersionFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*GetVersionFilesResponse_FileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"` // 文件分析结果
}

func (x *GetVersionFilesResponse) Reset() {
	*x = GetVersionFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_queryservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionFilesResponse) ProtoMessage() {}

func (x *GetVersionFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_queryservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionFilesResponse.ProtoReflect.Descriptor instead.
func (*GetVersionFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_service_queryservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionFilesResponse) GetFiles() []*GetVersionFilesResponse_FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetVersionFilesResponse_FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name               string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                          // 文件名
	Size               int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                                         // 文件大小，单位字节
	Etag               string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`                                                          // 文件校验码，一般是md5
	DownloadUrl        string `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`                         // 文件下载链接
	DownloadUrlExpires int32  `protobuf:"varint,5,opt,name=download_url_expires,json=downloadUrlExpires,proto3" json:"download_url_expires,omitempty"` // 文件下载链接有效时长，单位秒
}

func (x *GetVersionFilesResponse_FileInfo) Reset() {
	*x = GetVersionFilesResponse_FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_service_queryservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionFilesResponse_FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionFilesResponse_FileInfo) ProtoMessage() {}

func (x *GetVersionFilesResponse_FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_queryservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionFilesResponse_FileInfo.ProtoReflect.Descriptor instead.
func (*GetVersionFilesResponse_FileInfo) Descriptor() ([]byte, []int) {
	return file_api_service_queryservice_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetVersionFilesResponse_FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVersionFilesResponse_FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetVersionFilesResponse_FileInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetVersionFilesResponse_FileInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetVersionFilesResponse_FileInfo) GetDownloadUrlExpires() int32 {
	if x != nil {
		return x.DownloadUrlExpires
	}
	return 0
}

var File_api_service_queryservice_proto protoreflect.FileDescriptor

var file_api_service_queryservice_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x66, 0x69, 0x6c, 0x65, 0x78, 0x63, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x32, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x02, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x78, 0x63, 0x68, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x1a, 0x9b, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x74, 0x61, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x74, 0x61, 0x67, 0x12, 0x21, 0x0a, 0x0c,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12,
	0x30, 0x0a, 0x14, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x5f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x42, 0x1d, 0x5a, 0x1b, 0x66, 0x69, 0x6c, 0x65, 0x78, 0x63, 0x68, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_service_queryservice_proto_rawDescOnce sync.Once
	file_api_service_queryservice_proto_rawDescData = file_api_service_queryservice_proto_rawDesc
)

func file_api_service_queryservice_proto_rawDescGZIP() []byte {
	file_api_service_queryservice_proto_rawDescOnce.Do(func() {
		file_api_service_queryservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_service_queryservice_proto_rawDescData)
	})
	return file_api_service_queryservice_proto_rawDescData
}

var file_api_service_queryservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_service_queryservice_proto_goTypes = []interface{}{
	(*GetVersionsRequest)(nil),               // 0: filexch.api.service.GetVersionsRequest
	(*GetVersionsResponse)(nil),              // 1: filexch.api.service.GetVersionsResponse
	(*GetVersionFilesRequest)(nil),           // 2: filexch.api.service.GetVersionFilesRequest
	(*GetVersionFilesResponse)(nil),          // 3: filexch.api.service.GetVersionFilesResponse
	(*GetVersionFilesResponse_FileInfo)(nil), // 4: filexch.api.service.GetVersionFilesResponse.FileInfo
}
var file_api_service_queryservice_proto_depIdxs = []int32{
	4, // 0: filexch.api.service.GetVersionFilesResponse.files:type_name -> filexch.api.service.GetVersionFilesResponse.FileInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_service_queryservice_proto_init() }
func file_api_service_queryservice_proto_init() {
	if File_api_service_queryservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_service_queryservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_service_queryservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_service_queryservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_service_queryservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_service_queryservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionFilesResponse_FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_service_queryservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_service_queryservice_proto_goTypes,
		DependencyIndexes: file_api_service_queryservice_proto_depIdxs,
		MessageInfos:      file_api_service_queryservice_proto_msgTypes,
	}.Build()
	File_api_service_queryservice_proto = out.File
	file_api_service_queryservice_proto_rawDesc = nil
	file_api_service_queryservice_proto_goTypes = nil
	file_api_service_queryservice_proto_depIdxs = nil
}
